### ISSUE TITLE
"npm install" fails on client folder

### ISSUE THREAD

**Issue by moormaster** [shackspace/event-o-mat#23]
$ git clone https://github.com/shackspace/event-o-mat.git
$ cd event-o.mat/client
$ npm install

fails trying to build nodejs modules
1) integer
../src/integer.cpp:329:33: error: no matching function for call to 'v8::String::Value::Value(v8::Local<v8::String>&)'
  329 |   v8::String::Value utf16(string);

2) better-sqlite3
./src/util/database-handles.lzz:14:52: error: no matching function for call to 'v8::String::Utf8Value::Utf8Value(v8::Local<v8::String>&)'

3) farmhash
../../nan/nan_implementation_12_inl.h:103:42: error: cannot convert 'v8::Isolate*' to 'v8::Local<v8::Context>'
  103 |   return scope.Escape(v8::Function::New( isolate
      |                                          ^~~~~~~
      |                                          |
      |                                          v8::Isolate*

Is there something I am missing when I try to build the client page on my local machine?

**Comment by rashfael** [comment]
Looks like your nodejs version is too new. Either use node v9 (I think) or upgrade the dependencies.

**Comment by moormaster** [comment]
Worked for me
