### ISSUE TITLE
sort the website announcments by event date, not announcment order

### ISSUE THREAD

**Issue by excogitation** [shackspace/event-o-mat#7]
https://shackspace.de/archives/

as this is the expected way for the events to be sorted.

now: (sort by order entered)
ASRG Meeting 10: Automotive Network Architecture
15. Mai 19:00 - 21:00
TTN Meetup: #IOT Octopus - Ärmel hoch und bauen!
03. Mai 18:30 - 23:30
OpenHMD Hackathon
19. Mai 09:00 - 22:00

desired: (sort by event date)
OpenHMD Hackathon
19. Mai 09:00 - 22:00
ASRG Meeting 10: Automotive Network Architecture
15. Mai 19:00 - 21:00
TTN Meetup: #IOT Octopus - Ärmel hoch und bauen!
03. Mai 18:30 - 23:30

**Comment by excogitation** [comment]
It is a stream of announcments for events. When you reach the first one in the past you stop reading and do not check if there are upcoming events further down somewhere.

**Comment by rixx** [comment]
Exactly, it's a stream. Changing the order of the posts is super weird. I don't change the order of my blog posts just because I think one is more relevant.

**Comment by excogitation** [comment]
Having the order super weird is just illogical.
Sorting by date is the logical thing and improves usability.

**Comment by rixx** [comment]
I'd argue that if suddenly a post appears in the middle of posts I know I've already read, I'll never see it, but it seems it doesn't really matter.

**Comment by rashfael** [comment]
This was by design, it also screws less with RSS readers.
