### ISSUE TITLE
keyholder as dropdown to choose from

### ISSUE THREAD

**Issue by excogitation** [shackspace/event-o-mat#9]
e.g. exco is not the keyholder for LUGS, only the guy who entered it into events.
https://events.shackspace.de/events/13

**Comment by rixx** [comment]
Not a drop down, but a free text input.

**Comment by makefu** [comment]
right now keyholders have an id and a name (according to the api). maybe we do not need to do that, or add an extra field for "event created by".
Right now for all recurring events apparently i am the keyholder ;-)

**Comment by rixx** [comment]
That's what I meant by "free text input".

**Comment by rashfael** [comment]
keyholder is now free text.
